# Generated by Django 4.2.8 on 2023-12-18 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 12, 18, 17, 57, 57, 394532))),
                ('image', models.BinaryField()),
            ],
        ),
    ]
