# Generated by Django 4.2.8 on 2023-12-18 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSCHIR_PR11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 17, 58, 10, 979595)),
        ),
    ]
